'use strict';
let documentPage=0;
function briefSourcePreview(cites){const wrap=node('div');for(const c of cites.slice(0,2)){const text=c.title+' · r'+c.revision+' · line '+c.line+'\n“'+c.quote+'”';wrap.append(btt(text.length>150?text.slice(0,145)+'…':text,()=>readPages('Exact saved source',text),'evidence'));}if(cites.length>2)wrap.append(btt('All '+cites.length+' source quotes',()=>readPages('Exact evidence',cites.map(c=>c.title+' · r'+c.revision+' · line '+c.line+'\n'+c.quote).join('\n\n'))));return wrap;}
showSource=function(cite){const rev=state.documents.find(d=>cite.document_id?d.id===cite.document_id:d.title===cite.title)?.revisions.find(r=>r.number===cite.revision);readPages(cite.title+' · r'+cite.revision,(rev?.lines||[]).map(l=>l.line+'. '+l.text).join('\n'));};
compare=function(){const doc=state.documents.find(d=>d.id===selectedDoc),wrap=$('comparison');wrap.replaceChildren();$('source-pages').replaceChildren();if(!doc){$('compare-title').textContent='Exact source revisions';$('revision-label').textContent='No source selected';wrap.className='empty';wrap.textContent='Add your own source note, schedule or update. Earlier wording stays available.';return;}$('compare-title').textContent=doc.title;$('revision-label').textContent=doc.revisions.length>1?'r'+doc.revisions.at(-2).number+' → r'+doc.revisions.at(-1).number:'First revision';wrap.className='diff-grid';const revs=doc.revisions.length>1?doc.revisions.slice(-2):[null,doc.revisions[0]],limit=innerWidth<700?1:innerHeight<850?3:5,total=Math.max(...revs.map(r=>Math.ceil((r?.lines.length||0)/limit)),1);sourcePage=Math.min(sourcePage,total-1);for(const [i,rev] of revs.entries()){const col=node('div',undefined,'diff-col');col.append(node('h3',i?'CURRENT':'PREVIOUS'));for(const line of (rev?.lines||[]).slice(sourcePage*limit,(sourcePage+1)*limit)){const text=line.line+'. '+line.text;col.append(btt(text.length>(innerWidth<700?50:120)?text.slice(0,innerWidth<700?45:115)+'…':text,()=>readPages(doc.title+' · revision '+rev.number+' · line '+line.line,line.text),'source-line'));}if(!rev)col.append(node('p','First saved version.','muted'));wrap.append(col);}pager($('source-pages'),sourcePage,total,n=>{sourcePage=n;compare();});};
renderBrief=function(){const b=state.briefings.find(x=>x.id===selectedBrief),wrap=$('briefing');wrap.replaceChildren();$('brief-pages').replaceChildren();if(!b){wrap.className='empty';wrap.textContent='No saved handoff yet. Add your real source updates, then prepare a cited handoff.';return;}wrap.className='';if(b.outdated)wrap.append(node('p','Sources changed. Prepare a fresh handoff before acting on this checklist.','warning'));wrap.append(node('h3',b.headline,'brief-head'));const meta=b.created+' · '+(b.framework||'Strands Agents SDK')+' · '+(b.interpretation?'AI interpretation: review conclusions.':'Exact local source comparison.');wrap.append(btt('Handoff details',()=>readPages('Saved handoff',meta),'quiet'));const items=[...b.findings.map(x=>({kind:'finding',value:x})),...b.decisions.map(x=>({kind:'decision',value:x})),...b.open_questions.map(x=>({kind:'question',value:x}))];briefPage=Math.min(briefPage,Math.max(0,items.length-1));const item=items[briefPage];if(item){const x=item.value;wrap.append(node('h3',item.kind==='finding'?'Source finding':item.kind==='decision'?'Next-shift decision':'Still to resolve'));if(item.kind==='question')wrap.append(btt(x.length>180?x.slice(0,175)+'…':x,()=>readPages('Open question',x)));else{wrap.append(btt(x.text.length>180?x.text.slice(0,175)+'…':x.text,()=>readPages('Complete '+item.kind,x.text)));wrap.append(briefSourcePreview(x.evidence));if(item.kind==='decision'){const button=btt(x.done?'Reopen decision':'Mark reviewed decision done',async()=>{await api('decision',{briefing_id:b.id,decision_id:x.id,done:!x.done});await refresh();},'primary');button.disabled=b.outdated;wrap.append(button);}}}pager($('brief-pages'),briefPage,items.length,n=>{briefPage=n;renderBrief();});const link=node('a','Download complete handoff','export');link.href='/api/export?id='+encodeURIComponent(b.id);link.download='ShiftBrief-handoff.md';wrap.append(link);};
const renderBeforeSources=render;render=function(){renderBeforeSources();const wrap=$('documents'),buttons=[...wrap.children],limit=innerWidth<700?1:3,total=Math.ceil(buttons.length/limit);documentPage=Math.min(documentPage,Math.max(0,total-1));for(const [i,b] of buttons.entries()){b.hidden=i<documentPage*limit||i>=(documentPage+1)*limit;if(b.classList.contains('document')){const original=b.onclick;b.onclick=()=>{sourcePage=0;original();};}}let pg=$('document-pages');if(!pg){pg=node('div',undefined,'pager');pg.id='document-pages';wrap.after(pg);}pager(pg,documentPage,total,n=>{documentPage=n;render();});};
$('tool-details').querySelector('summary').onclick=e=>{e.preventDefault();readPages('How the handoff was made',$('runtime').textContent+'\n\n'+$('trace').innerText);};
const watchDetails=$('source-form').querySelector('details');watchDetails.querySelector('summary').onclick=e=>{e.preventDefault();const {body,d}=modal('Watch one exact local file'),file=node('input');file.placeholder='Full path to one chosen file';const title=node('input');title.placeholder='Source title';body.append(node('p','Only this exact selected file is checked. Originals and all revisions are kept.','muted'),file,title,btt('Watch this file',async()=>{await api('watch',{path:file.value,title:title.value,document_id:$('document-target').value||null});d.close();await refresh();},'primary'),btt('Review watched files',()=>readPages('Watched files',state.watches.map(w=>(w.enabled?'Watching ':'Paused ')+w.filename+(w.error?' · '+w.error:'')).join('\n'))));};
const originalProductionChange=$('production').onchange;$('production').onchange=()=>{formDraft=null;previewId=null;historyData=null;lastFormSignature='';documentPage=0;sourcePage=0;briefPage=0;originalProductionChange();};
const originalStatus=status;let statusTimer;status=function(text=''){clearTimeout(statusTimer);originalStatus(text);if(text){const close=btt('×',()=>status());close.className='status-close';close.setAttribute('aria-label','Dismiss status');$('status').append(close);statusTimer=setTimeout(()=>status(),8000);}};
const conversationWithStart=renderConversation;const previousConversationSignature=()=>chatSignature;renderConversation=function(){const previous=previousConversationSignature();conversationWithStart();if(previous!==chatSignature){const latest=state.assistant?.messages?.at(-1);if(latest){const max=innerWidth<700?innerHeight<650?230:550:innerWidth>=2400?1100:innerHeight<800?400:700;let rest=latest.text,count=0;while(rest){let n=Math.min(max,rest.length);if(n<rest.length){const x=rest.lastIndexOf(' ',n);if(x>n*.7)n=x;}rest=rest.slice(n).trimStart();count++;}if(count>1){chatPage=Math.max(0,chatPage-count+1);conversationWithStart();}}}};
if(state.staffing)render();

for(const e of watchDetails.children)if(e.tagName!=='SUMMARY')e.hidden=true;
$('sample').textContent='Example handoff';
const weekSummary=btt('Week totals',()=>readPages('Current week totals',$('project-progress').innerText));weekSummary.className='mobile-week-summary quiet';$('screen-schedule').querySelector('.toolbar').append(weekSummary);


const statusBeforeDialogs=status;status=function(text=''){const open=[...document.querySelectorAll('dialog[open]')].at(-1);document.querySelectorAll('.dialog-error').forEach(e=>e.remove());if(open&&text){const row=node('div',undefined,'dialog-error warning');row.setAttribute('role','alert');row.append(node('span',text.length>170?text.slice(0,165)+'…':text));if(text.length>170)row.append(btt('Read full message',()=>readPages('What needs attention',text)));open.querySelector('.dialog-body').prepend(row);statusBeforeDialogs();}else statusBeforeDialogs(text);};

const exportWeek=node('a','Export week','week-export quiet');exportWeek.href='#';exportWeek.onclick=e=>{e.preventDefault();window.shiftBriefBackend.download('/api/staff/export-week?week='+state.staffing.selected_week,'ShiftBrief-week-'+state.staffing.selected_week+'.zip');};$('screen-schedule').querySelector('.toolbar').append(exportWeek);

document.addEventListener('click',e=>{const a=e.target.closest('a[href^="/api/"]');if(a){e.preventDefault();window.shiftBriefBackend.download(a.getAttribute('href'),a.download||'ShiftBrief-export');}});
