'use strict';
let state={documents:[],briefings:[],watches:[]}, token='', selectedDoc='', selectedBrief='', busy=false;
const $=id=>document.getElementById(id);
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function status(text=''){$('status').textContent=text;}
async function api(path,body){const response=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-ShiftBrief-Token':token},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw Error(value.error||'Request failed.');return value;}
async function refresh(){const data=await api('state');state=data.state;token=data.token;$('runtime').textContent=data.runtime.label+' · model: '+data.runtime.model+' · '+data.runtime.url;if(!selectedDoc&&state.documents.length)selectedDoc=state.documents[0].id;if(!selectedBrief&&state.briefings.length)selectedBrief=state.briefings.at(-1).id;render();const running=data.jobs.find(x=>x.status==='running');if(running)renderJob(running);return data;}
function render(){
 $('production').replaceChildren();for(const p of state.productions)$('production').add(new Option(p.title,p.id));$('production').value=state.current_production;
 $('doc-count').textContent=state.documents.length;
 $('documents').replaceChildren();
 if(!state.documents.length)$('documents').append(node('p','No documents yet. Start with a call sheet or production note.','muted'));
 for(const d of state.documents){const b=node('button',undefined,'document'+(selectedDoc===d.id?' active':''));b.append(node('strong',d.title),node('small',d.revisions.length+' revision'+(d.revisions.length===1?'':'s')+' · '+d.revisions.at(-1).created));b.onclick=()=>{selectedDoc=d.id;render();};$('documents').append(b);}
 const target=$('document-target').value;$('document-target').replaceChildren(new Option('New document',''));for(const d of state.documents)$('document-target').add(new Option('New revision: '+d.title,d.id));$('document-target').value=target;
 $('watches').replaceChildren();for(const w of state.watches){const row=node('div',undefined,'watch-row');row.append(node('span',(w.enabled?'Watching ':'Paused ')+w.filename));const b=node('button',w.enabled?'Pause':'Resume','quiet');b.onclick=()=>act(async()=>{await api('watch/toggle',{id:w.id,enabled:!w.enabled});await refresh();});row.append(b,node('div',w.error||'Last checked '+w.last_checked,'muted'));$('watches').append(row);}
 renderProgress();compare();renderConversation();
 $('briefing-select').replaceChildren();for(const b of [...state.briefings].reverse())$('briefing-select').add(new Option(b.created+' — '+b.headline,b.id));$('briefing-select').value=selectedBrief;renderBrief();
 $('brief').disabled=busy||!state.documents.length;
}
function compare(){const doc=state.documents.find(d=>d.id===selectedDoc);if(!doc){$('compare-title').textContent='Your revisions, side by side';$('revision-label').textContent='No document selected';$('comparison').className='empty';$('comparison').textContent='Add an old and updated version to see exactly what changed.';return;}const revs=doc.revisions.slice(-2),before=revs.length>1?revs[0]:null,after=revs.at(-1);$('compare-title').textContent=doc.title;$('revision-label').textContent=(before?'r'+before.number+' → ':'First revision · ')+'r'+after.number;$('comparison').className='diff-grid';$('comparison').replaceChildren();for(const [rev,old] of [[before,true],[after,false]]){const col=node('div',undefined,'diff-col');col.append(node('h3',old?'PREVIOUS · '+(rev?'r'+rev.number:'none'):'CURRENT · r'+rev.number));const packet=state.comparisons?.find(p=>p.document_id===doc.id);const changed=new Set((packet?.changes||[]).flatMap(c=>Array.from({length:(old?c.before:c.after).length},(_,i)=>(old?c.before_start:c.after_start)+i)));for(const line of rev?.lines||[]){const row=node('div',undefined,'source-line'+(changed.has(line.line)?old?' old':' new':''));row.append(node('span',String(line.line)),document.createTextNode(line.text));col.append(row);}if(!rev)col.append(node('p','This is the first saved version.','muted'));$('comparison').append(col);}}
function showSource(cite){const dialog=node('dialog');const rev=state.documents.find(d=>cite.document_id?d.id===cite.document_id:d.title===cite.title)?.revisions.find(r=>r.number===cite.revision);dialog.append(node('h2',cite.title+' · revision '+cite.revision));const wrap=node('div');wrap.style.maxHeight='65vh';wrap.style.overflow='auto';for(const l of rev?.lines||[]){const row=node('div',l.line+'. '+l.text,'source-line'+(l.line===cite.line?' new':''));wrap.append(row);}dialog.append(wrap);const close=node('button','Close source','primary');close.onclick=()=>dialog.close();dialog.append(close);dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal();}
function evidence(cites){const wrap=node('div');for(const c of cites){const b=node('button',undefined,'evidence');b.append(node('b',c.title+' · r'+c.revision+' · line '+c.line+(c.page?' · PDF page '+c.page:'')),node('span','“'+c.quote+'”'));b.onclick=()=>showSource(c);wrap.append(b);}return wrap;}
function renderBrief(){const b=state.briefings.find(x=>x.id===selectedBrief);if(!b){$('briefing').className='empty';$('briefing').textContent='Add your documents, then Prepare handoff. Your change summary and checklist will be saved here.';$('progress').textContent='';$('trace').replaceChildren();return;}if(!busy){$('trace').replaceChildren();for(const t of b.trace)$('trace').append(node('li',t.detail));$('progress').textContent='Saved handoff · '+(b.elapsed_seconds??'?')+' seconds';}$('briefing').className='';$('briefing').replaceChildren();if(b.outdated)$('briefing').append(node('p','Documents have changed. This handoff is outdated; prepare a new one before using its decisions.','warning'));$('briefing').append(node('h3',b.headline,'brief-head'),node('p','Saved '+b.created+' · '+(b.elapsed_seconds?b.elapsed_seconds+' seconds · ':'')+(b.framework||'Strands Agents SDK'),'brief-meta'),node('p',b.interpretation?'AI interpretation. The quotes match saved source lines; please check the conclusions.':'Local source comparison. Quotes are preserved; review scope and approval before acting.','muted'));for(const f of b.findings){const row=node('div',undefined,'finding');row.append(node('p',f.text),evidence(f.evidence));$('briefing').append(row);}$('briefing').append(node('h3','Decisions for the next shift'));for(const d of b.decisions){const row=node('div',undefined,'decision'),check=node('input');check.type='checkbox';check.checked=d.done;check.disabled=b.outdated;check.setAttribute('aria-label',d.text);check.onchange=()=>act(async()=>{await api('decision',{briefing_id:b.id,decision_id:d.id,done:check.checked});await refresh();});const text=node('div');text.append(node('p',d.text,d.done?'done':''));if(d.owner_edited)text.append(node('small','Owner-edited checklist wording; matching current source evidence shown.','muted'));text.append(evidence(d.evidence));row.append(check,text);$('briefing').append(row);}if(b.open_questions.length){$('briefing').append(node('h3','Still to resolve'));const list=node('ul',undefined,'question-list');for(const q of b.open_questions)list.append(node('li',q));$('briefing').append(list);}const a=node('a','Export this handoff →','export');a.href='/api/export?id='+encodeURIComponent(b.id);a.download='ShiftBrief-handoff.md';$('briefing').append(a);}
function renderJob(job){$('progress').textContent=job.status==='running'?'Preparing your handoff… '+Math.floor(Date.now()/1000-job.started)+'s':job.status==='complete'?'Handoff saved. Your checklist is ready.':job.error;$('trace').replaceChildren();for(const t of job.trace)$('trace').append(node('li',t.detail));}
async function act(fn){try{status();await fn();}catch(e){status(e.message);$('production').value=state.current_production;}}
$('document-target').onchange=()=>{$('title').disabled=!!$('document-target').value;};
$('sample').onclick=()=>act(async()=>{await api('sample',{});selectedDoc='';selectedBrief='';await refresh();});
$('import').onclick=()=>act(async()=>{const body={title:$('title').value,document_id:$('document-target').value||null,text:$('paste').value,filename:'pasted.txt'};const file=$('file').files[0];if(file){if(file.size>5000000)throw Error('Choose a file smaller than 5 MB.');body.filename=file.name;const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));body.base64=btoa(binary);}const result=await api('import',body);selectedDoc=result.document_id;$('file').value='';$('paste').value='';status(result.unchanged?'This revision is already saved.':'Revision saved. Earlier versions are preserved.');await refresh();});
$('watch').onclick=()=>act(async()=>{await api('watch',{path:$('watch-path').value,title:$('title').value,document_id:$('document-target').value||null});await refresh();});
$('briefing-select').onchange=()=>{selectedBrief=$('briefing-select').value;renderBrief();};
$('brief').onclick=()=>act(async()=>{busy=true;$('brief').disabled=true;try{let job=await api('brief',{request:$('request').value,mode:$('engine-mode').value});renderJob(job);for(;;){await new Promise(r=>setTimeout(r,1000));const result=await api('state');job=result.jobs.find(x=>x.id===job.id);if(!job)throw Error('The app restarted before completing this handoff. Your sources are saved; prepare it again.');renderJob(job);if(job.status!=='running'){if(job.status==='error')throw Error(job.error);selectedBrief=job.briefing_id;await refresh();break;}}}finally{busy=false;$('brief').disabled=false;}});
$('production').onchange=()=>act(async()=>{await api('production/select',{id:$('production').value});selectedDoc='';selectedBrief='';await refresh();});
$('new-production').onclick=()=>{const dialog=node('dialog');dialog.append(node('h2','Name your production'));const input=node('input');input.placeholder='My short film — week 1';input.setAttribute('aria-label','Production name');const create=node('button','Create production','primary');create.onclick=()=>act(async()=>{await api('production/create',{title:input.value});selectedDoc='';selectedBrief='';dialog.close();await refresh();});const cancel=node('button','Cancel','quiet');cancel.onclick=()=>dialog.close();dialog.append(input,create,cancel);dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal();input.focus();};
refresh().catch(e=>status(e.message));setInterval(()=>{if(!busy)refresh().catch(e=>status(e.message));},15000);

function renderConversation(){const wrap=$('conversation');wrap.replaceChildren();const messages=state.assistant?.messages||[];if(!messages.length)wrap.append(node('p','Hi, I’m Sarah. We can start with your idea and build the first source note together. What does the next person need to know?','muted'));for(const m of messages.slice(-12)){const row=node('div',undefined,'chat-message '+m.role);row.append(node('strong',m.role==='user'?'You':'Sarah'),node('p',m.text));if(m.evidence?.length)row.append(evidence(m.evidence));wrap.append(row);}const area=$('proposal');area.replaceChildren();const p=state.assistant?.pending;if(p){area.append(node('h3',p.operation==='save_source_note'?'Review your source note':'Review this local checklist change'),node('p',p.operation==='save_source_note'?p.title+'\n'+p.text:p.operation==='set_done'?'Set decision '+p.decision_number+' '+(p.done?'done':'open')+'.':'Replace decision '+p.decision_number+' with: '+p.new_text));const label=node('label','Type YES to confirm');label.htmlFor='confirm-chat';const input=node('input');input.id='confirm-chat';input.placeholder='YES';const button=node('button',p.operation==='save_source_note'?'Save reviewed note':'Confirm checklist change','primary');button.onclick=()=>act(async()=>{const confirmed=await api('assistant/confirm',{proposal_id:p.id,proposal_sha:p.sha256,confirmation:input.value});await refresh();SarahVoice.read(confirmed.answer);});area.append(label,input,button);}wrap.scrollTop=wrap.scrollHeight;}
$('chat-send').onclick=()=>act(async()=>{const message=$('chat-message').value;$('chat-send').disabled=true;try{const answer=await api('assistant/message',{message,briefing_id:selectedBrief||null});$('chat-message').value='';await refresh();SarahVoice.read(answer.answer);}finally{$('chat-send').disabled=false;}});

function renderProgress(){const docs=state.documents.length,revisions=state.documents.reduce((n,d)=>n+d.revisions.length,0),current=state.briefings.filter(b=>!b.outdated),decisions=current.flatMap(b=>b.decisions),done=decisions.filter(d=>d.done).length;const steps=[['Sources',docs,docs>0],['Revisions',revisions,revisions>docs],['Current handoffs',current.length,current.length>0],['Reviewed decisions',done+'/'+decisions.length,!!decisions.length&&done===decisions.length]];$('project-progress').replaceChildren();for(const [label,value,complete] of steps){const card=node('div',undefined,'progress-stage'+(complete?' complete':''));card.append(node('span',complete?'✓':'○','progress-icon'),node('strong',String(value)),node('span',label));$('project-progress').append(card);}}
SarahVoice.configure({endpoint:'/api/voice/speak',headers:()=>({'X-ShiftBrief-Token':token}),getLatest:()=>state.assistant?.messages?.filter(m=>m.role==='assistant').at(-1)?.text||'Hi, I’m Sarah. We can start with your idea and build the first source note together. What does the next person need to know?'});
