const {chromium}=require(process.env.SHIFTBRIEF_PLAYWRIGHT||'playwright');
const fs=require('fs');const path=require('path');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});global.browser=browser;const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.SHIFTBRIEF_URL||'http://127.0.0.1:8797');await page.waitForFunction(()=>document.querySelector('#production').options.length>0);
const docs=[{title:'Campus screening plan',before:'Event: Lantern Campus Screening\nDoors: Friday October 2 at 18:00\nScreening: 18:30\nVenue: Arts Hall Room A\nAccessibility: step-free entrance at north door\nContact: Priya',after:'Event: Lantern Campus Screening\nDoors: Friday October 2 at 19:00\nScreening: 19:30\nVenue: Library auditorium\nAccessibility: step-free entrance not yet confirmed for new venue\nContact: Priya'},{title:'Volunteer rota',before:'Briefing: Friday October 2 at 17:15\nArrival checkpoint: Arts Hall Room A\nAssignments: two ushers at north door\nRota not updated after venue and time change.'},{title:'Equipment note',before:'Projector test due at 18:45 in Library auditorium.\nEquipment coordinator: Malik\nProjection setup is not yet confirmed complete.'}];
let proof={test:'Custom campus-event inputs, not the built-in sample',errors,local_model_required:true};
if(!process.argv.includes('--restart')){await page.getByRole('button',{name:'New production',exact:true}).click();await page.getByRole('textbox',{name:'Production name'}).fill('Campus screening — independent input test');await page.getByRole('button',{name:'Create production',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#production').selectedOptions[0].textContent.startsWith('Campus screening'));
for(const d of docs){await page.locator('#document-target').selectOption('');await page.locator('#title').fill(d.title);await page.locator('#paste').fill(d.before);await page.getByRole('button',{name:'Save this revision',exact:true}).click();await page.getByRole('button',{name:new RegExp(d.title)}).waitFor();if(d.after){await page.locator('#document-target').selectOption({label:'New revision: '+d.title});await page.locator('#paste').fill(d.after);await page.getByRole('button',{name:'Save this revision',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#revision-label').textContent==='r1 → r2');}}
await page.locator('#request').fill('Prepare a short handoff for this campus screening. Give the three most important findings and three practical next decisions. Flag unconfirmed accessibility and mismatched venue instructions; do not assume the later plan is approved or that any task has been completed.');const start=Date.now();await page.getByRole('button',{name:'Prepare handoff',exact:false}).click();await page.waitForFunction(()=>document.querySelector('.brief-head')||document.querySelector('#status').textContent,{timeout:180000});const error=await page.locator('#status').innerText();if(error)throw Error(error);proof.elapsed_ms=Date.now()-start;
await page.locator('.decision input').first().check();await page.waitForFunction(()=>document.querySelector('.decision .done'));await page.reload();await page.waitForFunction(()=>document.querySelector('.decision input')?.checked);proof.checklist_reload=true;
}else{await page.waitForFunction(()=>document.querySelector('.decision input')?.checked);proof.process_restart=true;}
proof.production=await page.locator('#production option:checked').innerText();proof.documents=await page.locator('.document').count();proof.findings=await page.locator('.finding p').allTextContents();proof.decisions=await page.locator('.decision p').allTextContents();proof.tool_trace=await page.locator('#trace li').allTextContents();const url=new URL(await page.locator('.export').getAttribute('href'),page.url()).href;proof.export_markdown=await(await page.request.get(url)).text();await page.locator('.evidence').first().click();await page.getByRole('dialog').waitFor();proof.source_dialog=true;await page.getByRole('button',{name:'Close source',exact:true}).click();const out=process.env.SHIFTBRIEF_EVIDENCE||path.join(__dirname,'evidence');fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,'SHIFTBRIEF-CUSTOM-WORKSPACE.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForFunction(()=>document.querySelector('.brief-head'));proof.mobile_overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);await page.screenshot({path:path.join(out,'SHIFTBRIEF-CUSTOM-MOBILE.png'),fullPage:true});fs.writeFileSync(path.join(out,process.argv.includes('--restart')?'SHIFTBRIEF-RESTART-RECEIPT.json':'SHIFTBRIEF-CUSTOM-RECEIPT.json'),JSON.stringify(proof,null,2));console.log(JSON.stringify(proof));await browser.close();if(errors.length||proof.mobile_overflow)process.exitCode=1;})().catch(async e=>{console.error(e);if(global.browser)await global.browser.close();process.exitCode=1});
