const {chromium}=require(process.env.SHIFTBRIEF_PLAYWRIGHT||'playwright');
const fs=require('fs'),path=require('path'),os=require('os'),{spawn}=require('child_process'),assert=require('assert');
const root=__dirname,out=path.join(root,'evidence','sarah-local-browser');fs.mkdirSync(out,{recursive:true});
const state=fs.mkdtempSync(path.join(os.tmpdir(),'shiftbrief-sarah-'));
let child,browser;
async function start(){let log='';child=spawn(path.join(root,'.venv','Scripts','python.exe'),['-u','-c','from server import make_server; import sys; s=make_server(sys.argv[1],0); print(s.server_port,flush=True); s.serve_forever()',state],{cwd:root,windowsHide:true,env:{...process.env,SHIFTBRIEF_OLLAMA_URL:'http://127.0.0.1:1'}});return await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server timeout '+log)),15000);child.stdout.on('data',b=>{log+=b;const m=log.match(/^\d+\r?\n/);if(m){clearTimeout(timer);resolve('http://127.0.0.1:'+m[0].trim());}});child.stderr.on('data',b=>log+=b);child.on('exit',c=>{if(c){clearTimeout(timer);reject(Error(log));}});});}
async function stop(){if(!child)return;await new Promise(resolve=>{child.once('exit',resolve);child.kill();});child=null;}
(async()=>{let url=await start();browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>document.querySelector('#production').options.length>0);
async function add(title,text,revision=false){await page.locator('#document-target').selectOption(revision?{label:'New revision: '+title}:'');if(!revision)await page.locator('#title').fill(title);await page.locator('#paste').fill(text);await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/import')&&r.request().method()==='POST'),page.locator('#import').click()]);await page.waitForFunction(()=>document.querySelector('#paste').value==='');}
await add('Screening schedule','Doors: 18:00\nVenue: Arts Hall Room A\nAccessibility: north door step-free\nCoordinator: Priya');await add('Screening schedule','Doors: 19:00\nVenue: Library auditorium\nAccessibility: step-free entrance not yet confirmed\nCoordinator: Priya',true);await add('Volunteer rota','Arrival checkpoint: Arts Hall Room A\nNew schedule not received.\nCoordinator: Priya');
assert.equal(await page.locator('#engine-mode').inputValue(),'sarah_local');await page.locator('#brief').click();await page.waitForSelector('.brief-head');assert.match(await page.locator('.brief-meta').innerText(),/Sarah local evidence engine/);assert((await page.locator('.finding').count())>1);assert((await page.locator('.decision').count())>1);
const questions=[];async function ask(q){await page.locator('#chat-message').fill(q);await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/assistant/message')),page.locator('#chat-send').click()]);await page.waitForFunction(()=>!document.querySelector('#chat-send').disabled);const answer=await page.locator('.chat-message.assistant>p').last().innerText();questions.push({question:q,answer});return answer;}
assert.match(await ask('What changed about accessibility?'),/not yet confirmed/);assert.match(await ask('Where is the volunteer checkpoint?'),/Arts Hall Room A/);assert.match(await ask('Where is that from?'),/Arts Hall Room A/);assert.match(await ask('Who approved xenonpayment on Neptune?'),/do not have source evidence/);
await ask('Mark decision 2 done');await page.locator('#confirm-chat').fill('YES');await page.getByRole('button',{name:'Confirm checklist change',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.decision input')[1].checked);
await ask('Revise decision 1: Ask Priya to verify the accessible entrance before doors open.');await page.locator('#confirm-chat').fill('YES');await page.getByRole('button',{name:'Confirm checklist change',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.decision p').textContent.includes('Ask Priya'));
const exportUrl=new URL(await page.locator('.export').getAttribute('href'),page.url()).href;const exported=await(await page.request.get(exportUrl)).text();assert.match(exported,/Ask Priya/);assert.match(exported,/- \[x\]/);assert.match(exported,/Owner-edited checklist wording/);fs.writeFileSync(path.join(out,'reviewed-handoff.md'),exported);
await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});await stop();url=await start();await page.goto(url);await page.waitForFunction(()=>document.querySelectorAll('.decision input')[1]?.checked);assert.match(await page.locator('.decision p').first().innerText(),/Ask Priya/);assert((await page.locator('.chat-message').count())>4);
await page.locator('.evidence').last().click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Close source',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForSelector('.brief-head');const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});assert.deepEqual(errors,[]);
const proof={tested:'Sarah local mode, actual browser and saved source documents',model_calls:0,ollama_url:'unreachable loopback port 1',questions,findings:await page.locator('.finding p').allTextContents(),checklist_confirmed:true,owner_revision_preserved:true,process_restart:true,source_dialog:true,markdown_export:true,mobile_overflow:overflow,errors};fs.writeFileSync(path.join(out,'receipt.json'),JSON.stringify(proof,null,2));console.log(JSON.stringify({passed:true,questions:questions.length,evidence:out}));await browser.close();browser=null;await stop();})().catch(async e=>{console.error(e);if(browser)await browser.close();await stop();process.exitCode=1;});
